if __name__ == "__main__":
    print("=== CYBER ARCHIVES - PRESERVATION SYSTEM ===\n")
    print("Initializing new storage unit: new_discovery.txt")
    print("Storage unit created successfully...\n")
    f = open('new_discovery.txt', 'w')
    print("Inscribing preservation data...")
    f.write("[ENTRY 001] New quantum algorithm discovered\n")
    f.write("[ENTRY 002] Efficiency increased by 347%\n")
    f.write("[ENTRY 003] Archived by Data Archivist trainee")
    f.close()
    f = open('new_discovery.txt', 'r')
    print(f.read())
    print("\nData inscription complete. Storage unit sealed.")
    print("Archive 'new_discovery.txt' ready for long-term preservation.")
    f.close()
